apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
        name: httpd-frontend
  template:
    metadata:
      labels:
          name: httpd-frontend
    spec:
      containers:
        - image: httpd:2.4-alpine
          name: httpd-frontend